set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER "$ENV{USERPROFILE}/scoop/apps/mingw/current/bin/x86_64-w64-mingw32-gcc.exe")
set(CMAKE_CXX_COMPILER "$ENV{USERPROFILE}/scoop/apps/mingw/current/bin/x86_64-w64-mingw32-g++.exe")

get_filename_component(MINGW_TOOLCHAIN_PATH ${CMAKE_C_COMPILER} DIRECTORY)
get_filename_component(MINGW_TOOLCHAIN_PATH ${MINGW_TOOLCHAIN_PATH} DIRECTORY)

set(TOOLCHAIN_SYSROOT  "${MINGW_TOOLCHAIN_PATH}/")
set(TOOLCHAIN_BIN_PATH "${MINGW_TOOLCHAIN_PATH}/bin")
set(TOOLCHAIN_INC_PATH "${MINGW_TOOLCHAIN_PATH}/x86_64-w64-mingw32/include")
set(TOOLCHAIN_LIB_PATH "${MINGW_TOOLCHAIN_PATH}/x86_64-w64-mingw32/lib")

set(CMAKE_SYSROOT ${TOOLCHAIN_SYSROOT})

find_program(CMAKE_OBJCOPY NAMES objcopy HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_OBJDUMP NAMES objdump HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_SIZE NAMES size HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_DEBUGGER NAMES gdb HINTS ${TOOLCHAIN_BIN_PATH})
find_program(CMAKE_CPPFILT NAMES c++filt HINTS ${TOOLCHAIN_BIN_PATH})
